# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'


tasks:
  run:
    desc: Run application
    cmds:
      - uv run fastapi dev
    silent: true

  build:
    desc: Build application
    cmds:
      - task lint
      - docker build -t spalaxdev/amail:1.3 .

  lint:
    desc: Run linter
    cmds:
      - uv run ruff check . --fix
